version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  hello-json:
    lang: python3
    handler: ./hello-json
    image: hello-json:latest
    labels:
      com.openfaas.scale.min: "1"
      com.openfaas.scale.zero: false
    environment:
      write_debug: true
      read_timeout: "60s"
      write_timeout: "60s"
      exec_timeout: "60s"
    secrets:
      - s3-axcel-id
      - s3-axcel-secret

